// ============================================================================
// Layer 1 — MemoryIndex: MEMORY.md manager
// ============================================================================

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { Result, ok, err } from 'neverthrow';
import type { MemoryIndexEntry } from '@nexus/core';
import { createLogger } from '@nexus/core';

const logger = createLogger({ service: 'memory-index' });

export class MemoryIndex {
  private readonly indexPath: string;
  private entries: Map<string, MemoryIndexEntry> = new Map();

  constructor(basePath: string) {
    this.indexPath = join(basePath, 'MEMORY.md');
  }

  public async load(): Promise<Result<void, Error>> {
    try {
      const raw = await readFile(this.indexPath, 'utf-8');
      this.entries = this.parseMarkdown(raw);
      logger.info({ entryCount: this.entries.size }, 'Memory index loaded');
      return ok(undefined);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        logger.info('No existing MEMORY.md found, starting fresh');
        this.entries = new Map();
        return ok(undefined);
      }
      const message = error instanceof Error ? error.message : 'Unknown error';
      return err(new Error(`Failed to load memory index: ${message}`));
    }
  }

  public getIndex(): ReadonlyMap<string, MemoryIndexEntry> {
    return this.entries;
  }

  public getIndexAsArray(): readonly MemoryIndexEntry[] {
    return Array.from(this.entries.values());
  }

  public async addTopic(
    slug: string,
    filePath: string,
    summary: string,
  ): Promise<Result<void, Error>> {
    if (this.entries.has(slug)) {
      return err(new Error(`Topic already exists: ${slug}`));
    }

    this.entries.set(slug, {
      slug,
      filePath,
      summary,
      lastUpdated: new Date().toISOString(),
    });

    return this.persist();
  }

  public async removeTopic(slug: string): Promise<Result<void, Error>> {
    if (!this.entries.has(slug)) {
      return err(new Error(`Topic not found: ${slug}`));
    }

    this.entries.delete(slug);
    return this.persist();
  }

  public async updateSummary(slug: string, summary: string): Promise<Result<void, Error>> {
    const entry = this.entries.get(slug);
    if (!entry) {
      return err(new Error(`Topic not found: ${slug}`));
    }

    this.entries.set(slug, {
      ...entry,
      summary,
      lastUpdated: new Date().toISOString(),
    });

    return this.persist();
  }

  // ---- Serialization ----

  private async persist(): Promise<Result<void, Error>> {
    try {
      await mkdir(dirname(this.indexPath), { recursive: true });
      const markdown = this.toMarkdown();
      await writeFile(this.indexPath, markdown, 'utf-8');
      logger.info({ entryCount: this.entries.size }, 'Memory index persisted');
      return ok(undefined);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      return err(new Error(`Failed to persist memory index: ${message}`));
    }
  }

  private toMarkdown(): string {
    const lines: string[] = [
      '# MEMORY INDEX',
      '',
      '> Auto-generated by NEXUS memory subsystem. Do not edit manually.',
      '',
      '| Slug | File Path | Summary | Last Updated |',
      '|------|-----------|---------|--------------|',
    ];

    for (const entry of this.entries.values()) {
      lines.push(
        `| ${entry.slug} | ${entry.filePath} | ${entry.summary} | ${entry.lastUpdated} |`,
      );
    }

    lines.push('');
    return lines.join('\n');
  }

  private parseMarkdown(raw: string): Map<string, MemoryIndexEntry> {
    const entries = new Map<string, MemoryIndexEntry>();
    const lines = raw.split('\n');

    for (const line of lines) {
      if (!line.startsWith('|') || line.startsWith('| Slug') || line.startsWith('|---')) {
        continue;
      }

      const cells = line
        .split('|')
        .map((c) => c.trim())
        .filter(Boolean);
      if (cells.length >= 4) {
        const entry: MemoryIndexEntry = {
          slug: cells[0]!,
          filePath: cells[1]!,
          summary: cells[2]!,
          lastUpdated: cells[3]!,
        };
        entries.set(entry.slug, entry);
      }
    }

    return entries;
  }
}
